In [1]:
import meld_graph
import meld_graph.models
import meld_graph.experiment
import meld_graph.dataset
import meld_graph.data_preprocessing
import meld_graph.icospheres

import importlib
importlib.reload(meld_graph)
importlib.reload(meld_graph.models)
importlib.reload(meld_graph.dataset)
importlib.reload(meld_graph.experiment)
importlib.reload(meld_graph.data_preprocessing)

from meld_graph.paths import EXPERIMENT_PATH
import numpy as np

import logging
import argparse
from copy import deepcopy
import os
from functools import reduce
import operator

Setting MELD_DATA_PATH to /home/co-spit1/meld_data
Setting BASE_PATH to /home/co-spit1/meld_data
Setting EXPERIMENT_PATH to /home/co-spit1/meld_experiments/co-spit1
Setting FS_SUBJECTS_PATH to /home/co-spit1/meld_data/output/fs_outputs
Setting EXPERIMENT_PATH to /rds/project/kw350/rds-kw350-meld/experiments_graph/co-spit1


In [2]:
def load_config(config_file):
    """load config.py file and return config object"""
    import importlib.machinery, importlib.util

    loader = importlib.machinery.SourceFileLoader("config", config_file)
    spec = importlib.util.spec_from_loader(loader.name, loader)
    config = importlib.util.module_from_spec(spec)
    loader.exec_module(config)
    return config

In [3]:
config = load_config("../scripts/config_files/experiment_config_hannah.py")

In [4]:
exp = meld_graph.experiment.Experiment(config.network_parameters, config.data_parameters, verbose=logging.INFO)

saving parameter files to /rds/project/kw350/rds-kw350-meld/experiments_graph/co-spit1/22-06-24_lr_decay/fold_00


In [5]:
config.data_parameters

{'hdf5_file_root': '{site_code}_{group}_featurematrix_combat_6.hdf5',
 'site_codes': ['H4'],
 'scanners': ['15T', '3T'],
 'dataset': 'MELD_dataset_V6.csv',
 'group': 'both',
 'features_to_exclude': [],
 'subject_features_to_exclude': [],
 'features': ['.on_lh.lesion.mgh', '.combat.on_lh.pial.K_filtered.sm20.mgh'],
 'features_to_replace_with_0': [],
 'number_of_folds': 10,
 'fold_n': 0,
 'preprocessing_parameters': {'scaling': None, 'zscore': True},
 'icosphere_parameters': {'distance_type': 'exact'},
 'augment_data': {},
 'combine_hemis': None,
 'lobes': False,
 'lesion_bias': 0}

In [6]:
trainer = meld_graph.training.Trainer(exp)

In [7]:
trainer.train()

Using coord type exact
getting train val test split
total number of subjects: 86
total number of subjects after restricting to subjects from MELD_dataset_V6.csv: 86
total number of subjects: 950
total number of subjects after restricting to subjects from MELD_dataset_V6.csv: 942
total number after filtering by scanner ['3T', '15T'], features, lesional_only True: 911
full_feature_list: ['.combat.on_lh.curv.sm5.mgh', '.combat.on_lh.gm_FLAIR_0.25.sm10.mgh', '.combat.on_lh.gm_FLAIR_0.5.sm10.mgh', '.combat.on_lh.gm_FLAIR_0.75.sm10.mgh', '.combat.on_lh.gm_FLAIR_0.sm10.mgh', '.combat.on_lh.pial.K_filtered.sm20.mgh', '.combat.on_lh.sulc.sm5.mgh', '.combat.on_lh.thickness.sm10.mgh', '.combat.on_lh.w-g.pct.sm10.mgh', '.combat.on_lh.wm_FLAIR_0.5.sm10.mgh', '.combat.on_lh.wm_FLAIR_1.sm10.mgh', '.inter_z.asym.intra_z.combat.on_lh.curv.sm5.mgh', '.inter_z.asym.intra_z.combat.on_lh.gm_FLAIR_0.25.sm10.mgh', '.inter_z.asym.intra_z.combat.on_lh.gm_FLAIR_0.5.sm10.mgh', '.inter_z.asym.intra_z.combat.on_lh

saved_new_best
Epoch 16 :: learning rate 0.0001
Epoch 16 :: Train loss 0.041, dice_lesion 0.043, dice_nonlesion 0.659, precision 0.023, recall 1.000, tp 112363.000, fp 4697762.000, fn 15.000, tn 15.000
Epoch 16 :: Val   loss 0.041, dice_lesion 0.002, dice_nonlesion 0.661, precision 0.001, recall 1.000, tp 697.000, fp 662759.000, fn 0.000, tn 0.000
saved_new_best
Epoch 17 :: learning rate 0.0001
Epoch 17 :: Train loss 0.039, dice_lesion 0.038, dice_nonlesion 0.670, precision 0.021, recall 1.000, tp 96432.000, fp 4580849.000, fn 6.000, tn 6.000
Epoch 17 :: Val   loss 0.039, dice_lesion 0.002, dice_nonlesion 0.669, precision 0.001, recall 1.000, tp 697.000, fp 651160.000, fn 0.000, tn 0.000
saved_new_best
Epoch 18 :: learning rate 0.0001
Epoch 18 :: Train loss 0.036, dice_lesion 0.047, dice_nonlesion 0.698, precision 0.026, recall 1.000, tp 112861.000, fp 4281873.000, fn 7.000, tn 7.000
Epoch 18 :: Val   loss 0.036, dice_lesion 0.003, dice_nonlesion 0.762, precision 0.001, recall 1.000, t

Epoch 39 :: Val   loss 0.015, dice_lesion 0.006, dice_nonlesion 0.889, precision 0.003, recall 1.000, tp 697.000, fp 262515.000, fn 0.000, tn 0.000
saved_new_best
Epoch 40 :: learning rate 0.0001
Epoch 40 :: Train loss 0.014, dice_lesion 0.095, dice_nonlesion 0.897, precision 0.057, recall 1.000, tp 103215.000, fp 1719333.000, fn 3.000, tn 3.000
Epoch 40 :: Val   loss 0.014, dice_lesion 0.006, dice_nonlesion 0.893, precision 0.003, recall 1.000, tp 697.000, fp 252426.000, fn 0.000, tn 0.000
saved_new_best
Epoch 41 :: learning rate 0.0001
Epoch 41 :: Train loss 0.013, dice_lesion 0.104, dice_nonlesion 0.899, precision 0.062, recall 1.000, tp 111445.000, fp 1681508.000, fn 6.000, tn 6.000
Epoch 41 :: Val   loss 0.014, dice_lesion 0.007, dice_nonlesion 0.898, precision 0.003, recall 1.000, tp 697.000, fp 242737.000, fn 0.000, tn 0.000
saved_new_best
Epoch 42 :: learning rate 0.0001
Epoch 42 :: Train loss 0.013, dice_lesion 0.100, dice_nonlesion 0.908, precision 0.059, recall 1.000, tp 983

Epoch 63 :: Val   loss 0.009, dice_lesion 0.017, dice_nonlesion 0.965, precision 0.008, recall 1.000, tp 697.000, fp 89191.000, fn 0.000, tn 0.000
saved_new_best
Epoch 64 :: learning rate 0.0001
Epoch 64 :: Train loss 0.008, dice_lesion 0.254, dice_nonlesion 0.968, precision 0.181, recall 1.000, tp 125789.000, fp 570339.000, fn 4.000, tn 4.000
Epoch 64 :: Val   loss 0.008, dice_lesion 0.018, dice_nonlesion 0.966, precision 0.008, recall 1.000, tp 697.000, fp 85006.000, fn 0.000, tn 0.000
saved_new_best
Epoch 65 :: learning rate 0.0001
Epoch 65 :: Train loss 0.008, dice_lesion 0.228, dice_nonlesion 0.969, precision 0.174, recall 1.000, tp 115304.000, fp 548522.000, fn 3.000, tn 3.000
Epoch 65 :: Val   loss 0.008, dice_lesion 0.019, dice_nonlesion 0.968, precision 0.009, recall 1.000, tp 697.000, fp 80962.000, fn 0.000, tn 0.000
saved_new_best
Epoch 66 :: learning rate 0.0001
Epoch 66 :: Train loss 0.008, dice_lesion 0.216, dice_nonlesion 0.971, precision 0.160, recall 1.000, tp 99495.00

Epoch 87 :: Val   loss 0.006, dice_lesion 0.044, dice_nonlesion 0.990, precision 0.025, recall 1.000, tp 697.000, fp 27098.000, fn 0.000, tn 0.000
saved_new_best
Epoch 88 :: learning rate 0.0001
Epoch 88 :: Train loss 0.006, dice_lesion 0.428, dice_nonlesion 0.991, precision 0.426, recall 1.000, tp 122821.000, fp 165646.000, fn 10.000, tn 10.000
Epoch 88 :: Val   loss 0.006, dice_lesion 0.046, dice_nonlesion 0.990, precision 0.026, recall 1.000, tp 697.000, fp 25719.000, fn 0.000, tn 0.000
saved_new_best
Epoch 89 :: learning rate 0.0001
Epoch 89 :: Train loss 0.006, dice_lesion 0.426, dice_nonlesion 0.992, precision 0.417, recall 1.000, tp 109875.000, fp 153443.000, fn 8.000, tn 8.000
Epoch 89 :: Val   loss 0.006, dice_lesion 0.048, dice_nonlesion 0.991, precision 0.028, recall 1.000, tp 697.000, fp 24376.000, fn 0.000, tn 0.000
saved_new_best
Epoch 90 :: learning rate 0.0001
Epoch 90 :: Train loss 0.006, dice_lesion 0.417, dice_nonlesion 0.993, precision 0.434, recall 1.000, tp 102773

Epoch 111 :: Val   loss 0.005, dice_lesion 0.098, dice_nonlesion 0.997, precision 0.079, recall 1.000, tp 697.000, fp 8084.000, fn 0.000, tn 0.000
saved_new_best
Epoch 112 :: learning rate 0.0001
Epoch 112 :: Train loss 0.005, dice_lesion 0.521, dice_nonlesion 0.998, precision 0.679, recall 1.000, tp 91841.000, fp 43413.000, fn 9.000, tn 9.000
Epoch 112 :: Val   loss 0.005, dice_lesion 0.101, dice_nonlesion 0.997, precision 0.083, recall 1.000, tp 697.000, fp 7734.000, fn 0.000, tn 0.000
saved_new_best
Epoch 113 :: learning rate 0.0001
Epoch 113 :: Train loss 0.005, dice_lesion 0.529, dice_nonlesion 0.998, precision 0.682, recall 1.000, tp 93180.000, fp 43353.000, fn 10.000, tn 10.000
Epoch 113 :: Val   loss 0.005, dice_lesion 0.103, dice_nonlesion 0.997, precision 0.086, recall 1.000, tp 697.000, fp 7402.000, fn 0.000, tn 0.000
saved_new_best
Epoch 114 :: learning rate 0.0001
Epoch 114 :: Train loss 0.005, dice_lesion 0.510, dice_nonlesion 0.998, precision 0.657, recall 1.000, tp 7856

Epoch 135 :: Train loss 0.004, dice_lesion 0.700, dice_nonlesion 0.999, precision 0.877, recall 1.000, tp 107955.000, fp 15203.000, fn 17.000, tn 17.000
Epoch 135 :: Val   loss 0.004, dice_lesion 0.159, dice_nonlesion 0.999, precision 0.176, recall 1.000, tp 697.000, fp 3271.000, fn 0.000, tn 0.000
saved_new_best
Epoch 136 :: learning rate 0.0001
Epoch 136 :: Train loss 0.004, dice_lesion 0.624, dice_nonlesion 0.999, precision 0.886, recall 1.000, tp 109055.000, fp 13964.000, fn 17.000, tn 17.000
Epoch 136 :: Val   loss 0.004, dice_lesion 0.163, dice_nonlesion 0.999, precision 0.181, recall 1.000, tp 697.000, fp 3159.000, fn 0.000, tn 0.000
saved_new_best
Epoch 137 :: learning rate 0.0001
Epoch 137 :: Train loss 0.004, dice_lesion 0.640, dice_nonlesion 0.999, precision 0.899, recall 1.000, tp 99607.000, fp 11248.000, fn 16.000, tn 16.000
Epoch 137 :: Val   loss 0.004, dice_lesion 0.167, dice_nonlesion 0.999, precision 0.187, recall 1.000, tp 697.000, fp 3033.000, fn 0.000, tn 0.000
sav

saved_new_best
Epoch 159 :: learning rate 0.0001
Epoch 159 :: Train loss 0.003, dice_lesion 0.650, dice_nonlesion 1.000, precision 0.941, recall 1.000, tp 99024.000, fp 6236.000, fn 20.000, tn 20.000
Epoch 159 :: Val   loss 0.004, dice_lesion 0.418, dice_nonlesion 1.000, precision 0.352, recall 1.000, tp 697.000, fp 1283.000, fn 0.000, tn 0.000
saved_new_best
Epoch 160 :: learning rate 0.0001
Epoch 160 :: Train loss 0.003, dice_lesion 0.711, dice_nonlesion 1.000, precision 0.952, recall 1.000, tp 107098.000, fp 5411.000, fn 25.000, tn 25.000
Epoch 160 :: Val   loss 0.004, dice_lesion 0.418, dice_nonlesion 1.000, precision 0.356, recall 1.000, tp 697.000, fp 1259.000, fn 0.000, tn 0.000
saved_new_best
Epoch 161 :: learning rate 0.0001
Epoch 161 :: Train loss 0.003, dice_lesion 0.686, dice_nonlesion 1.000, precision 0.951, recall 1.000, tp 113677.000, fp 5894.000, fn 35.000, tn 35.000
Epoch 161 :: Val   loss 0.004, dice_lesion 0.418, dice_nonlesion 1.000, precision 0.362, recall 1.000, t

saved_new_best
Epoch 183 :: learning rate 0.0001
Epoch 183 :: Train loss 0.003, dice_lesion 0.740, dice_nonlesion 1.000, precision 0.970, recall 1.000, tp 103528.000, fp 3208.000, fn 37.000, tn 37.000
Epoch 183 :: Val   loss 0.003, dice_lesion 0.433, dice_nonlesion 1.000, precision 0.548, recall 1.000, tp 697.000, fp 575.000, fn 0.000, tn 0.000
saved_new_best
Epoch 184 :: learning rate 0.0001
Epoch 184 :: Train loss 0.003, dice_lesion 0.743, dice_nonlesion 1.000, precision 0.970, recall 0.999, tp 115045.000, fp 3563.000, fn 62.000, tn 62.000
Epoch 184 :: Val   loss 0.003, dice_lesion 0.433, dice_nonlesion 1.000, precision 0.555, recall 1.000, tp 697.000, fp 558.000, fn 0.000, tn 0.000
saved_new_best
Epoch 185 :: learning rate 0.0001
Epoch 185 :: Train loss 0.003, dice_lesion 0.678, dice_nonlesion 1.000, precision 0.972, recall 0.999, tp 118053.000, fp 3380.000, fn 68.000, tn 68.000
Epoch 185 :: Val   loss 0.003, dice_lesion 0.434, dice_nonlesion 1.000, precision 0.560, recall 1.000, tp

saved_new_best
Epoch 207 :: learning rate 0.0001
Epoch 207 :: Train loss 0.003, dice_lesion 0.672, dice_nonlesion 1.000, precision 0.976, recall 0.999, tp 103616.000, fp 2554.000, fn 83.000, tn 83.000
Epoch 207 :: Val   loss 0.003, dice_lesion 0.453, dice_nonlesion 1.000, precision 0.694, recall 1.000, tp 697.000, fp 308.000, fn 0.000, tn 0.000
saved_new_best
Epoch 208 :: learning rate 0.0001
Epoch 208 :: Train loss 0.003, dice_lesion 0.743, dice_nonlesion 1.000, precision 0.981, recall 1.000, tp 98547.000, fp 1917.000, fn 49.000, tn 49.000
Epoch 208 :: Val   loss 0.003, dice_lesion 0.455, dice_nonlesion 1.000, precision 0.701, recall 1.000, tp 697.000, fp 298.000, fn 0.000, tn 0.000
saved_new_best
Epoch 209 :: learning rate 0.0001
Epoch 209 :: Train loss 0.003, dice_lesion 0.756, dice_nonlesion 1.000, precision 0.986, recall 1.000, tp 104085.000, fp 1446.000, fn 49.000, tn 49.000
Epoch 209 :: Val   loss 0.003, dice_lesion 0.455, dice_nonlesion 1.000, precision 0.705, recall 1.000, tp 

saved_new_best
Epoch 231 :: learning rate 0.0001
Epoch 231 :: Train loss 0.002, dice_lesion 0.778, dice_nonlesion 1.000, precision 0.987, recall 0.999, tp 113376.000, fp 1542.000, fn 89.000, tn 89.000
Epoch 231 :: Val   loss 0.003, dice_lesion 0.475, dice_nonlesion 1.000, precision 0.829, recall 1.000, tp 697.000, fp 144.000, fn 0.000, tn 0.000
saved_new_best
Epoch 232 :: learning rate 0.0001
Epoch 232 :: Train loss 0.002, dice_lesion 0.721, dice_nonlesion 1.000, precision 0.986, recall 0.999, tp 86749.000, fp 1254.000, fn 50.000, tn 50.000
Epoch 232 :: Val   loss 0.003, dice_lesion 0.476, dice_nonlesion 1.000, precision 0.832, recall 1.000, tp 697.000, fp 141.000, fn 0.000, tn 0.000
saved_new_best
Epoch 233 :: learning rate 0.0001
Epoch 233 :: Train loss 0.002, dice_lesion 0.687, dice_nonlesion 1.000, precision 0.986, recall 0.999, tp 103317.000, fp 1502.000, fn 54.000, tn 54.000
Epoch 233 :: Val   loss 0.003, dice_lesion 0.477, dice_nonlesion 1.000, precision 0.841, recall 1.000, tp 

saved_new_best
Epoch 255 :: learning rate 0.0001
Epoch 255 :: Train loss 0.002, dice_lesion 0.823, dice_nonlesion 1.000, precision 0.992, recall 0.999, tp 89412.000, fp 722.000, fn 62.000, tn 62.000
Epoch 255 :: Val   loss 0.002, dice_lesion 0.497, dice_nonlesion 1.000, precision 0.978, recall 1.000, tp 697.000, fp 16.000, fn 0.000, tn 0.000
saved_new_best
Epoch 256 :: learning rate 0.0001
Epoch 256 :: Train loss 0.002, dice_lesion 0.717, dice_nonlesion 1.000, precision 0.991, recall 0.999, tp 89778.000, fp 774.000, fn 62.000, tn 62.000
Epoch 256 :: Val   loss 0.002, dice_lesion 0.497, dice_nonlesion 1.000, precision 0.980, recall 1.000, tp 697.000, fp 14.000, fn 0.000, tn 0.000
saved_new_best
Epoch 257 :: learning rate 0.0001
Epoch 257 :: Train loss 0.002, dice_lesion 0.786, dice_nonlesion 1.000, precision 0.991, recall 0.999, tp 108331.000, fp 991.000, fn 115.000, tn 115.000
Epoch 257 :: Val   loss 0.002, dice_lesion 0.497, dice_nonlesion 1.000, precision 0.980, recall 1.000, tp 697.

saved_new_best
Epoch 279 :: learning rate 0.0001
Epoch 279 :: Train loss 0.002, dice_lesion 0.755, dice_nonlesion 1.000, precision 0.996, recall 0.999, tp 96676.000, fp 362.000, fn 79.000, tn 79.000
Epoch 279 :: Val   loss 0.002, dice_lesion 0.500, dice_nonlesion 1.000, precision 1.000, recall 1.000, tp 697.000, fp 0.000, fn 0.000, tn 0.000
saved_new_best
Epoch 280 :: learning rate 0.0001
Epoch 280 :: Train loss 0.002, dice_lesion 0.755, dice_nonlesion 1.000, precision 0.991, recall 0.999, tp 91943.000, fp 857.000, fn 74.000, tn 74.000
Epoch 280 :: Val   loss 0.002, dice_lesion 0.500, dice_nonlesion 1.000, precision 1.000, recall 1.000, tp 697.000, fp 0.000, fn 0.000, tn 0.000
saved_new_best
Epoch 281 :: learning rate 0.0001
Epoch 281 :: Train loss 0.002, dice_lesion 0.655, dice_nonlesion 1.000, precision 0.998, recall 0.999, tp 90156.000, fp 206.000, fn 72.000, tn 72.000
Epoch 281 :: Val   loss 0.002, dice_lesion 0.500, dice_nonlesion 1.000, precision 1.000, recall 1.000, tp 697.000, 

saved_new_best
Epoch 303 :: learning rate 0.0001
Epoch 303 :: Train loss 0.002, dice_lesion 0.723, dice_nonlesion 1.000, precision 0.998, recall 0.999, tp 94969.000, fp 170.000, fn 82.000, tn 82.000
Epoch 303 :: Val   loss 0.002, dice_lesion 0.500, dice_nonlesion 1.000, precision 1.000, recall 1.000, tp 697.000, fp 0.000, fn 0.000, tn 0.000
saved_new_best
Epoch 304 :: learning rate 0.0001
Epoch 304 :: Train loss 0.002, dice_lesion 0.723, dice_nonlesion 1.000, precision 0.996, recall 0.999, tp 86790.000, fp 334.000, fn 86.000, tn 86.000
Epoch 304 :: Val   loss 0.002, dice_lesion 0.500, dice_nonlesion 1.000, precision 1.000, recall 1.000, tp 697.000, fp 0.000, fn 0.000, tn 0.000
saved_new_best
Epoch 305 :: learning rate 0.0001
Epoch 305 :: Train loss 0.002, dice_lesion 0.758, dice_nonlesion 1.000, precision 1.000, recall 0.999, tp 101629.000, fp 0.000, fn 147.000, tn 147.000
Epoch 305 :: Val   loss 0.002, dice_lesion 0.500, dice_nonlesion 1.000, precision 1.000, recall 1.000, tp 697.000,

saved_new_best
Epoch 327 :: learning rate 0.0001
Epoch 327 :: Train loss 0.002, dice_lesion 0.827, dice_nonlesion 1.000, precision 0.999, recall 0.999, tp 110477.000, fp 115.000, fn 100.000, tn 100.000
Epoch 327 :: Val   loss 0.002, dice_lesion 0.500, dice_nonlesion 1.000, precision 1.000, recall 1.000, tp 697.000, fp 0.000, fn 0.000, tn 0.000
saved_new_best
Epoch 328 :: learning rate 0.0001
Epoch 328 :: Train loss 0.002, dice_lesion 0.689, dice_nonlesion 1.000, precision 0.999, recall 0.999, tp 95037.000, fp 130.000, fn 96.000, tn 96.000
Epoch 328 :: Val   loss 0.002, dice_lesion 0.500, dice_nonlesion 1.000, precision 1.000, recall 1.000, tp 697.000, fp 0.000, fn 0.000, tn 0.000
saved_new_best
Epoch 329 :: learning rate 0.0001
Epoch 329 :: Train loss 0.002, dice_lesion 0.827, dice_nonlesion 1.000, precision 0.999, recall 0.999, tp 120113.000, fp 136.000, fn 168.000, tn 168.000
Epoch 329 :: Val   loss 0.002, dice_lesion 0.500, dice_nonlesion 1.000, precision 1.000, recall 1.000, tp 697

saved_new_best
Epoch 351 :: learning rate 0.0001
Epoch 351 :: Train loss 0.002, dice_lesion 0.827, dice_nonlesion 1.000, precision 1.000, recall 0.999, tp 120251.000, fp 10.000, fn 173.000, tn 173.000
Epoch 351 :: Val   loss 0.002, dice_lesion 0.500, dice_nonlesion 1.000, precision 1.000, recall 1.000, tp 697.000, fp 0.000, fn 0.000, tn 0.000
saved_new_best
Epoch 352 :: learning rate 0.0001
Epoch 352 :: Train loss 0.002, dice_lesion 0.689, dice_nonlesion 1.000, precision 1.000, recall 0.999, tp 100128.000, fp 22.000, fn 95.000, tn 95.000
Epoch 352 :: Val   loss 0.002, dice_lesion 0.500, dice_nonlesion 1.000, precision 1.000, recall 1.000, tp 697.000, fp 0.000, fn 0.000, tn 0.000
saved_new_best
Epoch 353 :: learning rate 0.0001
Epoch 353 :: Train loss 0.002, dice_lesion 0.621, dice_nonlesion 1.000, precision 1.000, recall 0.999, tp 84333.000, fp 22.000, fn 93.000, tn 93.000
Epoch 353 :: Val   loss 0.002, dice_lesion 0.500, dice_nonlesion 1.000, precision 1.000, recall 1.000, tp 697.000,

saved_new_best
Epoch 375 :: learning rate 0.0001
Epoch 375 :: Train loss 0.002, dice_lesion 0.586, dice_nonlesion 1.000, precision 0.998, recall 0.999, tp 81148.000, fp 135.000, fn 94.000, tn 94.000
Epoch 375 :: Val   loss 0.002, dice_lesion 0.500, dice_nonlesion 1.000, precision 1.000, recall 1.000, tp 697.000, fp 0.000, fn 0.000, tn 0.000
saved_new_best
Epoch 376 :: learning rate 0.0001
Epoch 376 :: Train loss 0.002, dice_lesion 0.724, dice_nonlesion 1.000, precision 1.000, recall 0.998, tp 109500.000, fp 37.000, fn 175.000, tn 175.000
Epoch 376 :: Val   loss 0.002, dice_lesion 0.500, dice_nonlesion 1.000, precision 1.000, recall 1.000, tp 697.000, fp 0.000, fn 0.000, tn 0.000
saved_new_best
Epoch 377 :: learning rate 0.0001
Epoch 377 :: Train loss 0.002, dice_lesion 0.690, dice_nonlesion 1.000, precision 1.000, recall 0.999, tp 107133.000, fp 0.000, fn 104.000, tn 104.000
Epoch 377 :: Val   loss 0.002, dice_lesion 0.500, dice_nonlesion 1.000, precision 1.000, recall 1.000, tp 697.00

saved_new_best
Epoch 399 :: learning rate 0.0001
Epoch 399 :: Train loss 0.001, dice_lesion 0.689, dice_nonlesion 1.000, precision 1.000, recall 0.999, tp 104276.000, fp 2.000, fn 111.000, tn 111.000
Epoch 399 :: Val   loss 0.001, dice_lesion 0.500, dice_nonlesion 1.000, precision 1.000, recall 1.000, tp 697.000, fp 0.000, fn 0.000, tn 0.000
saved_new_best


In [9]:
for p in exp.model.parameters():
    print(p)


Parameter containing:
tensor([[-0.1594],
        [-0.0392]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([ 0.3608, -0.4987], device='cuda:0', requires_grad=True)


In [9]:
idxs = trainer.val_data_loader.dataset.lesional_idxs

lesions = list(trainer.val_data_loader.dataset[idxs])

print(lesions[0].x[lesions[0].y > 0].mean(axis=0))
print(lesions[0].x[lesions[0].y == 0].mean(axis=0))

tensor([10.9818, 11.1576])
tensor([0.0000, 0.4085])


In [10]:
idxs = trainer.train_data_loader.dataset.lesional_idxs

lesions = list(trainer.train_data_loader.dataset[idxs])

print(lesions[0].x[lesions[0].y > 0].mean(axis=0))
print(lesions[0].x[lesions[0].y == 0].mean(axis=0))

tensor([10.9865, 10.2297])
tensor([0.0000, 0.2891])


In [46]:
data_true = lesions[0].y
sum(data_true)

tensor(650)

In [47]:
data_pred = exp.model(lesions[0].x.to(exp.model.device))[0]
data_pred = np.argmax(data_pred.cpu().detach(), axis=1)

In [48]:
sum(data_pred)

tensor(733)

In [49]:
sum(~(data_true == data_pred))

tensor(83)

In [50]:
lesions[0].x

tensor([[-0.0469, -0.9361],
        [-0.0469,  2.6119],
        [-0.0469, -0.1069],
        ...,
        [-0.0469, -0.2335],
        [-0.0469, -0.1417],
        [-0.0469, -0.0278]])

In [51]:
lesions[1].x

tensor([[-0.0126, -1.1752],
        [-0.0126, -1.1540],
        [-0.0126, -0.2428],
        ...,
        [-0.0126,  0.8933],
        [-0.0126,  0.9001],
        [-0.0126,  1.0584]])